### ISSUE TITLE
copy issue in the "select dosage" field

### ISSUE THREAD

**Issue by bermanc76** [keslavi/HHMerch#1]
On the actual product detail pages, under the "select dosage" field, the copy is getting cut off.   this is happening for all product categories, in both Chrome and IE.  I haven't tested Firefox.

Also, I think we should bring the "Description" copy section below up a bit higher.

![image](https://user-images.githubusercontent.com/30842871/29540271-72e657da-8682-11e7-9edd-4efac463d1bf.png)

**Comment by bermanc76** [comment]
I just reviewed it and we are still having the same issue.  Under "Select Dosage" the copy in the drop down menu is cut off.  Also, there is a lot of space betwen the "Add to Cart" button and the Description copy below.  We should fix these two issues before we push live.

**Comment by keslavi** [comment]
alvin, could you take a look at this one?

**Comment by vinespn** [comment]
My apology if I have overlooked this one. 

"Select Dosage" dropdown field copy getting cut off issue has been fixed. I tested in Chrome, Firefox and Safari. Please check and confirm in IE as I don't have one.

Also, "Description" copy section has been moved a bit higher.

Thanks

**Comment by bermanc76** [comment]
This looks good.  The issue is closed as far as I'm concerned.  Steve - can you please push this to the live merch site if other issues are resolved?

**Comment by bermanc76** [comment]
This looks good.  Thanks Alvin.

The issue is closed as far as I'm concerned.  I have closed it out in
Github.  Steve - can you please push this to the live merch site if other
issues are resolved?
